### PR TITLE
Enable more targets in quickinstall

### PR DESCRIPTION
**Pull request by NobodyXu**
- aarch64-pc-windows-msvc
 - aarch64-unknown-linux-musl
 - armv7-unknown-linux-musleabihf
 - armv7-unknown-linux-gnueabihf

Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>

### CODE REVIEW

**Comment by Milo123459** [comment]
For Raspberry Pis, you need to add "aarch64-unknown-linux-gnu"

**Comment by NobodyXu** [comment]
> For Raspberry Pis, you need to add "aarch64-unknown-linux-gnu"

It's already supported.
I also add the corresponding musl target.

**Comment by NobodyXu** [comment]
Build for `aarch64-unknown-linux-musl` is confirmed to be working.

**Review by Milo123459 — APPROVED** [review]

**Comment by NobodyXu** [comment]
Build for `aarch64-pc-windows-msvc` has also confirmed to be working.

**Comment by NobodyXu** [comment]
Building `ring` v0.16.20 on `aarch64-pc-windows-msvc` failed, which is expected since it doesn't support that target yet.
Support will be added in ring v0.16.21 or v0.17.0

**Comment by NobodyXu** [comment]
Build for `armv7-unknown-linux-musleabihf` has confirmed to be working.

**Comment by NobodyXu** [comment]
Build for `armv7-unknown-linux-gnueabihf` has confirmed to be working.

**Pull request merged**
