### PR TITLE
try using tmate to let Milo debug arm linux things interactively

### PR DESCRIPTION
**Pull request by alsuren**
I have no idea whether this is going to work, but if it does, it will improve @Milo123459's iteration time on the aarch builds

### CODE REVIEW

**Comment by alsuren** [comment]
@Milo123459 okay, that worked for me.

If you push a commit to this branch then you will become the "actor", and it will let you ssh into the github actions runner and try stuff out interactively:

you will be able to go to the github actions output like this:

https://github.com/cargo-bins/cargo-quickinstall/actions/runs/4033788378/jobs/6934538880#step:3:49

and see something like `ssh KsjVb7unuxPrW8as7BSjSkvBW@sfo2.tmate.io`. If you ssh to the place that it says, it should let you into a tmux session. Press q and it will give you a bash prompt, and you can run stuff exactly as it would in a github actions runner.

**Comment by Milo123459** [comment]
oh wow, cool! thanks!

can i merge this into my branch? or will that not help

**Comment by alsuren** [comment]
@Milo123459 just completely delete .github/workflows/test.yml for now - the linter failure is cancelling the tmate session :(

**Comment by Milo123459** [comment]
well, it works now lol

**Pull request closed without merging**
